---
name: Feature Request
description: Propose a new feature or a change to existing functionality
body:
  - type: textarea
    attributes:
      label: What should be added/changed?
      description: Describe in details the feature you like to be added or changed
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: >
        Describe the reason of making the change you've mentioned above.
        How this change could help Validity users?
    validations:
      required: true
